---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Water Quality of Clinton River following Black Marsh Restoration"
subtitle: "Web address for GitHub repository"
author: "Nadia Swit"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(cowplot)
library(dataRetrieval)
library(sf)
library(maps)

# Set your ggplot theme
theme_set(theme_classic())

# Load your datasets
ClintonFlow_summary <- read.csv("./Processed_Data/ClintonRiverFlow_Processed.csv")
ClintonWQFlow_long <-read.csv("./Processed_Data/ClintonRiverWQ_Processed.csv")

```


# Rationale and Research Questions
he National Oceanic and Atmospheric Administration (NOAA) has performing several large-scale restoration projects in the Great Lakes Region. Focusing on Areas of Concern (AOC), which are environmentally degraded areas within the Great Lakes Basin, these systems have several impairments to their beneficial uses as a result of human activity at the local level. Restoration is carried out through the Great Lakes Restoration Initiative, and is aimed at improving and delisting these impairments and AOCs. Clinton River, located in Michigan, and hydrologically connected to St. Clair Lake and Lake Erie, is projected to be delisted as an AOC in 2027-2030.

Clinton River is located just north of Detroit in Southeastern Michigan ad drains 760 square miles of watershed. The river was designated an AOC through the Great Lakes Water Quality Agreement in 1987 due to ecological impairments caused by heavy metal, PCB, and pollution. The Clinton River AOC includes the mainstem and its tributaries, the Spillway, which includes a 2-mile long canal that connects the Clinton River and Lake St. Clair, and the nearshore of Lake St. Clair between mouth of the St. Clair River and the Spillway outlet (Virgilio, 2022). 

Currently, only on beneficial use impairment (BUI) has been removed, Degredaton of Aesthetics, which occurred in 2020. However, there are 7 remaining BUIs before the Clinton River can be delisted as an AOC. However, there were 18 habitat restoration projects, including invasive species management, dam removal, and wetland restoration. As of 2020, all 18 restoration projects and a stream stabilization project were completed, which acted to delist the Degredation of Aesthetics BUI. However, there are still concerns over sedimentation and remaining heavy metal pollution, which is addressed in an ongoing project. One restoration project included the Black Creek Marsh Habitat Restoration, which restored about 2 acres of coastal wetland marsh and spawning habitat, encouraging increased recreation at Lake St. Clair Metropark. Spawning habitat for yellow perch ad northern pike was addressed in the Black Creek channel, and sediment was dredged to remove legacy seed banks for Phragmites, as well as creating channels and ponds for wildlife habitat. Funded by the Great Lakes Restoration Initiative (GLRI), U.S. Environmental Protection Agency (EPA), NOAA, and Great Lakes Commission (GLC), the project goals were provide environmental, economic, and community benefits by restoring and enhanving wetland and wildlife habitat, improving recreation, and increasing recreation for the community and improving water quality (Ellis and Colliton, 2019).

The Black Marsh Coastal Wetland Restoration Project received $648,000 and was awarded to the Huron-Clinton Metropolitan Authority (HCMA) in 2014. The HCMA purchased private propety containing significant marsh habitat, which led to the long-term hydrological restoration. There have been no published updates since the project besides the release that all restoration projects pertaining to the aesthetic of the Clinton River AOC were completed. However, results of this restoration project could greatly influence future restoration work for Michigan, including the Lake St. Clair. 

This analysis aims to evaluate several questions related to the restoration project and water quality in the Clinton River near the Black Marsh Coastal Wetland Restoration Project.
1. How have the water quality parameters changed before and post construction process? Has it improved?
2. What are the locations of water quality gages near Lake St. Clair and its tributaries?


\newpage

# Dataset Information

Data was obtained from the Water Quality Portal and USGS Stream Gage. The closest gage in proximity to the restoration site, Black Marsh, was the Clinton River at Sterling Heights gage (ID: 04161820). Project background was obtained from NOAA Restoration Center. 




\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References

Ellis, E. and Colliton, R. (2019). Black Creek Marsh Habitat Restoration. NOAA-Great Lakes Commission Regional Partnership. Retrieved from https://www.glc.org/wp-content/uploads/GLC-NOAA-Partnership-Clinton-River-Factsheet-December-2019.pdf

NOAA (2022). Habitat restoration in Areas of Concern. NOAA. Retrieved from https://www.noaa.gov/habitat-restoration-in-areas-of-concern

Virgilio, S. (2020). Clinton River AOC. EPA. Retrieved from https://www.epa.gov/great-lakes-aocs/clinton-river-aoc